apiVersion: v1
kind: Service
metadata:
  name: graphite-server-carbon
  labels:
    app.kubernetes.io/name: graphite-server-carbon
spec:
  type: ClusterIP
  ports:
    - name: graphite-pickle
      port: 2004
      protocol: TCP
    - name: graphite-plain
      port: 2003
      protocol: TCP
    - name: graphite-udp
      port: 2003
      protocol: UDP
    - name: aggregate-plain
      port: 2023
      protocol: TCP
    - name: aggregate-pickl
      port: 2024
      protocol: TCP
  selector:
    app.kubernetes.io/name: graphite
    app.kubernetes.io/instance: graphite
