---
# Define a 'Service' To Expose postgres to Other Services
apiVersion: v1
kind: Service
metadata:
  name: postgresql-stolon-proxy-nodeport
  labels:
    app: postgresql-stolon-proxy
    chart: stolon-0.8.1
    component: stolon-proxy
    heritage: Tiller
    release: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30013
      protocol: TCP
  selector:
    app: postgresql-stolon-proxy
    chart: stolon-0.8.1
    component: stolon-proxy
    release: postgresql
    stolon-cluster: postgresql-stolon
