apiVersion: apps/v1
kind: Deployment
metadata:
  name: easystogu-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: easystogu-portal
  template:
    metadata:
      labels:
        app: easystogu-portal
    spec:
      containers:
      - name: easystogu-portal
        image: eyaweiw.cn:5000/easystogu-portal:2.0.0-snapshot 
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: jdbc.url
            valueFrom:
              configMapKeyRef:
                name: easystogu-configmap
                key: jdbc.url
          - name: jdbc.user
            valueFrom:
              configMapKeyRef:
                name: easystogu-configmap
                key: jdbc.user
          - name: jdbc.password
            valueFrom:
              configMapKeyRef:
                name: easystogu-configmap
                key: jdbc.password
          - name: jdbc.maxActive
            valueFrom:
              configMapKeyRef:
                name: easystogu-configmap
                key: jdbc.maxActive
          - name: jdbc.maxIdle
            valueFrom:
              configMapKeyRef:
                name: easystogu-configmap
                key: jdbc.maxIdle

