##easystogu VirtualService
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: easystogu-portal
spec:
  hosts:
  - "*"
  gateways:
  - easystogu-portal-gateway
  http:
  - name: "easystogu-portal-v2-routes"
  - match:
    - uri:
        prefix: /portal
    route:
    - destination:
        host: easystogu-portal
        subset: v2
        port:
          number: 8080
