---
apiVersion: v1
kind: Service
metadata:
  name: easystogu-portal-loadbalancer
  labels:
    app: easystogu-portal
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: easystogu-portal
  externalTrafficPolicy: Local

