##easystogu VirtualService
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: easystogu-scheduled
spec:
  hosts:
  - "*" 
  gateways:
  - my-ingress-istio-gateway
  http:
  - match:
    - uri:
        prefix: /scheduled/health
    rewrite:
      uri: /health
    route:
    - destination:
        host: easystogu-scheduled
        port:
          number: 8080
