##easystogu VirtualService
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: easystogu-scheduled
spec:
  hosts:
  - easystogu-scheduled
  gateways:
  - easystogu-scheduled-gateway
  http:
  - route:
    - destination:
        host: easystogu-scheduled
        subset: v2
        port:
          number: 8080
