---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-nodeport
spec:
  type: NodePort
  ports:
    - port: 9042
      targetPort: 9042
      nodePort: 30014
  selector:
    interface: cassandra
